language: php
php:
- 5.3
- 5.4
- 5.5
- 5.6
before_install:
- openssl aes-256-cbc -K $encrypted_2f11dc29dfab_key -iv $encrypted_2f11dc29dfab_iv
  -in tests/oauth.cache.enc -out tests/oauth.cache -d
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f4645bdfa8b59b13f684
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
